[package]
name = "rust_nbt"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
flate2 = "1.0.35"
indexmap = { version = "2.7.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
